import pandas as pd
import matplotlib.pyplot as plt

# Read the clean text file generated by the echo commands
df = pd.read_csv('task3_sweep.txt', sep=r'\s+', header=0)

# Plot VDD vs Delta V
plt.figure(figsize=(8, 5))
plt.plot(df['vdd'], df['dv'] * 1000, marker='o', linewidth=2, label='Measured Delta V')
plt.axhline(y=25, color='r', linestyle='--', label='25 mV Sense-Amp Offset')

plt.title('Bitline Differential vs. Supply Voltage')
plt.xlabel('VDD (V)')
plt.ylabel('Delta V (mV)')
plt.grid(True)
plt.legend()
plt.savefig('sram_sweep_task3.png')

# Find where Delta V falls below the 25 mV threshold
df['dv_mV'] = df['dv'] * 1000
failing_points = df[df['dv_mV'] < 25]

print("\n--- Failure Analysis ---")
if failing_points.empty:
    print("Delta V never fell below 25 mV in the tested sweep range (1.1 V to 0.6 V).")
else:
    print("Delta V falls below 25 mV at the following voltages:")
    print(failing_points[['vdd', 'dv_mV']].to_string(index=False))